USE test;

-- SQL TO ADD A PRIMARY KEY TO A TABLE
ALTER TABLE <tablename>
ADD PRIMARY KEY (columnname);

-- SQL TO REMOVE A PRIMARY KEY TO A TABLE
ALTER TABLE <tablename>
DROP PRIMARY KEY (columnname);

DESCRIBE addresses;
ALTER TABLE addresses
ADD PRIMARY KEY (id);

ALTER TABLE addresses
DROP PRIMARY KEY;

DESCRIBE people;
ALTER TABLE people
ADD PRIMARY KEY (id);
